package com.example.Assignment2Bun.service;

import com.example.Assignment2Bun.model.RegularUser;
import com.example.Assignment2Bun.model.User;
import com.example.Assignment2Bun.repo.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import javax.transaction.Transactional;
import java.util.Optional;

@Service
public class UserService {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    public void save(RegularUser n) {
        userRepository.save(n);
    }

    public Iterable<User> findAll() {
        return userRepository.findAll();
    }
    public Optional<User> findByUsername(String username) {
        return userRepository.findByUsername(username);
    }
    @Transactional
    public Optional<User> deleteByUsername(String username) {
        return userRepository.deleteByUsername(username);
    }
}
